Models/Base/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models.Base
{
    public class BaseEntity
    {
        public int Id { get; set; }
    }
}

Models/Category.cs
using pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models
{
    public class Category:BaseEntity
    {
        public int Name { get; set; }
        public List<PlantCategory> PlantCategories { get; set; }
    }
}

Models/Plant.cs
using pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models
{
    public class Plant:BaseEntity
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Desc { get; set; }
        public string SKU { get; set; }
        public int  PlantInformationId{ get; set; }
        public PlantInformation PlantInformation { get; set; }
        public List<PlantImage> PlantImages { get; set; }
        public List<PlantCategory> PlantCategories { get; set; }

    }
}

Models/PlantCategory.cs
using pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models
{
    public class PlantCategory:BaseEntity
    {
        public int PlantId { get; set; }
        public Plant Plant { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

Models/PlantImage.cs
using pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models
{
    public class PlantImage:BaseEntity
    {
        public string Name { get; set; }
        public string Alternative { get; set; }
        public bool? IsMain { get; set; }
        public int PlantId { get; set; }
        public Plant Plant { get; set; }
    }
}

Models/PlantInformation.cs
using pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models
{
    public class PlantInformation:BaseEntity
    {
        public string Shipping { get; set; }
        public string AboutReturnRequst { get; set; }
        public string Guarentee { get; set; }
        public List<Plant> Plants { get; set; }
    }
}

Models/Setting.cs
using pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models
{
    public class Setting : BaseEntity
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }
}

Models/Silder.cs
using pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Models
{
    public class Silder:BaseEntity
    {
        public string Image { get; set; }
        public string Discount { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public string ButtonUrl { get; set; }
        public byte Order { get; set; }
    }
}

ViewModels/BasketCookieItemVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.ViewModels
{
    public class BasketCookieItemVM
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
    }
}

ViewModels/BasketItemVM.cs
using pronia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.ViewModels
{
    public class BasketItemVM
    {
        public Plant Plant { get; set; }
        public int Quantity { get; set; }
    }
}

ViewModels/BasketVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.ViewModels
{
    public class BasketVM
    {
        public List<BasketCookieItemVM> BasketCookieItemVMs { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

ViewModels/HomeVM.cs
using pronia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.ViewModels
{
    public class HomeVM
    {
        public List<Silder> Silders { get; set; }
        public List<Plant> Plants { get; set; }
    }
}

ViewModels/LayoutBasketVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.ViewModels
{
    public class LayoutBasketVM
    {
        public List<BasketItemVM> BasketItemVMs { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P127_Pronia.DAL;
using pronia.Models;
using pronia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        { 
            HomeVM model = new HomeVM { 
            Silders= _context.Silders.ToList(),
            Plants = _context.Plants.Include(p =>p.PlantImages).ToList()
            };
            return View(model);
        }
    }
}

Controllers/PlantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P127_Pronia.DAL;
using pronia.Models;
using pronia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pronia.Controllers
{
    public class PlantController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlantController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }
            Plant  plant =await _context.Plants.Include(p => p.PlantImages)
                .Include(p => p.PlantInformation)
                .Include(p => p.PlantCategories).ThenInclude(p=>p.Category)
                .FirstOrDefaultAsync(p=>p.Id==id);
            if (plant == null) return NotFound();
            return View(plant);
        }
        public async Task<IActionResult> Partial()
        {
            List<Plant> plants = await _context.Plants.Include(p => p.PlantImages).ToListAsync();
            return View("_PlantsPartialView",plants);
        }
        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Plant plant = await _context.Plants.FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            string basketStr = HttpContext.Request.Cookies["Basket"];

            BasketVM basket;

            if (string.IsNullOrEmpty(basketStr))
            {
                basket = new BasketVM();
                BasketCookieItemVM cookieItem = new BasketCookieItemVM
                {
                    Id = plant.Id,
                    Quantity = 1
                };
                basket.BasketCookieItemVMs = new List<BasketCookieItemVM>();
                basket.BasketCookieItemVMs.Add(cookieItem);
                basket.TotalPrice = plant.Price;

            }
            else
            {
                basket = JsonConvert.DeserializeObject<BasketVM>(basketStr);
                BasketCookieItemVM existed = basket.BasketCookieItemVMs.Find(p => p.Id == id);
                if (existed == null)
                {
                    BasketCookieItemVM cookieItem = new BasketCookieItemVM
                    {
                        Id = plant.Id,
                        Quantity = 1
                    };
                    basket.BasketCookieItemVMs.Add(cookieItem);
                    basket.TotalPrice += plant.Price;
                }
                else
                {
                    basket.TotalPrice += plant.Price;
                    existed.Quantity++;
                }
            }
            basketStr = JsonConvert.SerializeObject(basket);

            HttpContext.Response.Cookies.Append("Basket", basketStr);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult ShowBasket()
        {
            if (HttpContext.Request.Cookies["Basket"] == null) return NotFound();
            BasketVM basket = JsonConvert.DeserializeObject<BasketVM>(HttpContext.Request.Cookies["Basket"]);
            return Json(basket);
        }
    }
}

Views/Shared/_PlantsPartialView.cshtml
@foreach (Plant plant in Model)
                   {
                       <div class="col-xl-3 col-md-4 col-sm-6">
                      <div class="product-item">
                        <div class="product-img">
                          <a href="shop.html">
                            <img
                              class="primary-img"
                              src="~/assets/images/website-images//@plant.PlantImages.FirstOrDefault(x=>x.IsMain==true).Name"
                              alt="@plant.PlantImages.FirstOrDefault(x=>x.IsMain==true).Alternative"
                            />
                            <img
                              class="secondary-img"
                              src="~/assets/images/website-images//@plant.PlantImages.FirstOrDefault(x=>x.IsMain==null)?.Name"
                              alt="@plant.PlantImages.FirstOrDefault(x=>x.IsMain==null)?.Alternative"
                            />
                          </a>
                          <div class="product-add-action">
                            <ul>
                              <li>
                                <a
                                  href="wishlist.html"
                                  data-tippy="Add to wishlist"
                                  data-tippy-inertia="true"
                                  data-tippy-animation="shift-away"
                                  data-tippy-delay="50"
                                  data-tippy-arrow="true"
                                  data-tippy-theme="sharpborder"
                                >
                                  <i class="pe-7s-like"></i>
                                </a>
                              </li>
                              <li
                                class="quuickview-btn"
                                data-bs-toggle="modal"
                                data-bs-target="#quickModal"
                              >
                                <a
                                  href="#"
                                  data-tippy="Quickview"
                                  data-tippy-inertia="true"
                                  data-tippy-animation="shift-away"
                                  data-tippy-delay="50"
                                  data-tippy-arrow="true"
                                  data-tippy-theme="sharpborder"
                                >
                                  <i class="pe-7s-look"></i>
                                </a>
                              </li>
                              <li>
                                <a
                                  asp-controller="Plant" asp-action="AddBasket" asp-route-id="@plant.Id"
                                  data-tippy="Add to cart"
                                  data-tippy-inertia="true"
                                  data-tippy-animation="shift-away"
                                  data-tippy-delay="50"
                                  data-tippy-arrow="true"
                                  data-tippy-theme="sharpborder"
                                >
                                  <i class="pe-7s-cart"></i>
                                </a>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div class="product-content">
                          <a class="product-name" href="shop.html"
                            >@plant.Name</a
                          >
                          <div class="price-box pb-1">
                            <span class="new-price">$@plant.Price</span>
                          </div>
                          <div class="rating-box">
                            <ul>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                   }